name: create-release
on:
  push:
    tags:
      - v*
permissions:
  contents: read
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3
        id: app-token
        with:
          client-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
      - uses: orhun/git-cliff-action@c93ef52f3d0ddcdcc9bd5447d98d458a11cd4f72 # v4
        id: git-cliff
        with:
          args: --current --strip all
        env:
          OUTPUT: /tmp/release-notes.md
      - run: sudo apt-get update && sudo apt-get install libpixman-1-dev libwayland-dev meson scdoc wayland-protocols
      - name: prepare a tarball
        run: |
          meson setup --buildtype release build
          meson dist -C build --allow-dirty
      - uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe # v2
        with:
          body_path: /tmp/release-notes.md
          fail_on_unmatched_files: true
          files: |
            build/meson-dist/still-*.tar.xz
            build/meson-dist/still-*.tar.xz.sha256sum
          token: ${{ steps.app-token.outputs.token }}
