name: push
on:
  push:
    branches:
      - "**"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
permissions:
  contents: read
jobs:
  build:
    if: github.ref_name == github.event.repository.default_branch
    uses: ./.github/workflows/build.yaml
  bump-version:
    if: github.ref_name == github.event.repository.default_branch
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3
        id: app-token
        with:
          client-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
      - uses: orhun/git-cliff-action@a9a95522b26fe6403f7bb24031f21fb573d0f5ff # v4
        id: git-cliff
        with:
          args: --bump
        env:
          OUTPUT: CHANGELOG.md
      - name: bump version
        env:
          version: ${{ steps.git-cliff.outputs.version }}
        run: |
          sed -i -e "s/^\(\s\+version\): '.*'/\1: '${version#v}'/" meson.build
          git add CHANGELOG.md meson.build

          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

          if git commit -m "chore: $version"; then
            git push origin

            git tag "$version"
            git push origin --tags
          fi
